package View;

public enum ProgramRequestType {
    SHOW_DUPLICATE_NAME, SHOW_ACCOUNT, SHOW_INVALID_NAME, SHOW_INVALID_CHOICE, SHOW_INVALID_UNDO, SHOW_WINNER,
    SHOW_INVALID_COMMAND, SHOW_OTHELLO_GAME, SHOW_PROGRESS
}
